### ISSUE TITLE
"Problems loading reference"

### ISSUE THREAD

**Issue by NatoBoram** [HuJohner/vscode-mc-datapack-ext#5]
Hi! I just installed the extension and it gives me an error when I open an advancement `.json` file.

> Problems loading reference `file:///c%3A/Users/natob/.vscode-insiders/extensions/pca.datapack-helper-0.6.1/ref/shared/minecraft_definitions.json#/definitions/namespaced_location`: Unable to load schema from `c:\Users\natob\.vscode-insiders\extensions\pca.datapack-helper-0.6.1\ref\shared\minecraft_definitions.json`: ENOENT: no such file or directory, open `c:\Users\natob\.vscode-insiders\extensions\pca.datapack-helper-0.6.1\ref\shared\minecraft_definitions.json`.

```yaml
Version: 1.52.0-insider
Commit: dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66
Date: 2020-12-10T17:20:40.435Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
